export const environment = {
  production: true,
  url: 'https://apiadmincja.sloppy.zone/',
  urlLibreta: 'https://conalepjalisco.superatemexico.com/',
	libreta_URI: 'https://conalepjalisco.superatemexico.com/#',
	vendor: 'ACL Systems SA de CV',
  idTutor: '5afade18be6da5001b81e59f',
	versionCheckURL: 'version.json',
	instanceName: 'conalep',
	instanceTitle: 'Conalep Jalisco',
	siteName: 'conalepjalisco.superatemexico.com',
	footer: 'Conalep Jalisco',
	captchaSiteKey: '6LctRtIUAAAAAPMCpI8Ogk6-2_4SM8o0GmP0DU5F',
	publicKey: 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBTldjcE5ZQlhjN2tEK3dNZC9HOGlGU0xIc1lJWlZuOQp0SWE1WjB2RDVxNFVwUG8wdDQwS21XVXZqVlVQWHZtM2FydUJOcjI3dmtoTHpvUmgrUDU0eElNQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=',
	logo: '/assets/img/conalep_brand.jpg',
	color: 'info',
	eventColor: '#16A2B8',
	colorEvents: ['#16A2B8', '#04B45F', '#BE1C1F', '#E6E6E6'],
	textColor: '#FFFFFF',
	selfRegister: true,
	emailSupport: 'soporte@superatemexico.com'
};
