import { Display } from '@crmshared/types/display.type';

export const STATES: Display[] = [
	{value: 'AS', viewValue: 'Aguascalientes'},
	{value: 'BC', viewValue: 'Baja California'},
	{value: 'BS', viewValue: 'Baja California Sur'},
	{value: 'CC', viewValue: 'Campeche'},
	{value: 'CS', viewValue: 'Chiapas'},
	{value: 'CH', viewValue: 'Chihuahua'},
	{value: 'DF', viewValue: 'Ciudad de México'},
	{value: 'CL', viewValue: 'Coahuila'},
	{value: 'CM', viewValue: 'Colima'},
	{value: 'DG', viewValue: 'Durango'},
	{value: 'GT', viewValue: 'Guanajuato'},
	{value: 'GR', viewValue: 'Guerrero'},
	{value: 'HG', viewValue: 'Hidalgo'},
	{value: 'JC', viewValue: 'Jalisco'},
	{value: 'MX', viewValue: 'México'},
	{value: 'MN', viewValue: 'Michoacán'},
	{value: 'MS', viewValue: 'Morelos'},
	{value: 'NT', viewValue: 'Nayarit'},
	{value: 'NL', viewValue: 'Nuevo León'},
	{value: 'OC', viewValue: 'Oaxaca'},
	{value: 'PL', viewValue: 'Puebla'},
	{value: 'QO', viewValue: 'Querétaro'},
	{value: 'QR', viewValue: 'Quintana Roo'},
	{value: 'SP', viewValue: 'San Luis Potosí'},
	{value: 'SL', viewValue: 'Sinaloa'},
	{value: 'SR', viewValue: 'Sonora'},
	{value: 'TC', viewValue: 'Tabasco'},
	{value: 'TS', viewValue: 'Tamaulipas'},
	{value: 'TL', viewValue: 'Tlaxcala'},
	{value: 'VZ', viewValue: 'Veracruz'},
	{value: 'YN', viewValue: 'Yucatán'},
	{value: 'ZS', viewValue: 'Zacatecas'}
]
